name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Run Expo prebuild
        run: npx expo prebuild

      - name: Build Android APK
        run: npx react-native build-android --tasks assembleRelease

      - name: Rename Outputs
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/mxadmin.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/release/mxadmin.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
